version: '3.8'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
# OLD:    command: python manage.py run -h 0.0.0.0
    command: gunicorn --bind 0.0.0.0:5000 manage:app
# OLD:    volumes:
# OLD:      - ./services/web/:/usr/src/app/
    # expose - internal to other docker services only. not to host machine.
    # use ports for mapping to host machine.
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
# OLD:    environment:
# OLD:      - POSTGRES_USER=hello_flask
# OLD:      - POSTGRES_PASSWORD=hello_flask
# OLD:      - POSTGRES_DB=hello_flask_dev
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:

